### ISSUE TITLE
Add functionality pivot

### ISSUE THREAD

**Issue by rcorzogutierrez** [burke-software/django-report-builder#200]
Assess the possibility of including pivot functionality on the results of the reports. I found this builder of reports that could provide some visual ideas for this project.
http://bi2.io/webpivottable
http://nicolas.kruchten.com/pivottable/examples/

**Comment by bufke** [comment]
Could you explain this more? This project already is able to do joins.

**Comment by grantjenks** [comment]
Closing due to lack of details and we can do joins. While it would be interesting to integrate a more powerful grid (like pivottable), it doesn't currently feel critical to the project. You can already export to Google Docs or Excel via the CSV file to do pivots. We also don't have a way to record the pivot transformations that are applied after pulling data from the database.
