### ISSUE TITLE
please provide bower.json of dependencies

### ISSUE THREAD

**Issue by mbande** [burke-software/django-report-builder#266]
it would make extending report builder's user interface much easier

**Comment by bufke** [comment]
Is this worth doing? I'd prefer to throw out bowser and use webpack if I ever get the time. That said if you want to submit a bower.json I would accept it. Make sure to include why it's helpful.

**Comment by mbande** [comment]
bower is the most used package manager in the javascript world (at least i think so).
I tried to add bower.json, but faced many dependency issues.

**Comment by bufke** [comment]
Most of the JS world these days is going with npm/yarn packages. Interesting discussion: https://github.com/bower/bower/issues/2298

I'm going to close this ticket because I don't find bower appealing in 2017. If I get time I'd like to declare dependencies in package.json and bundle things for distribution on pypi. It's a pain right now listing files in MANIFEST.in and upgrading packages with bower. 

If you wanted to sort through bower dependency issues, I would accept a pull request because it's still an improvement.
