### ISSUE TITLE
python_requires='>=3.3' in setup.py

### ISSUE THREAD

**Issue by predatell** [burke-software/django-report-builder#275]
What is the reason for this? Why I can not use for example python 2.7?

**Comment by bufke** [comment]
The big reason is I don't have time to maintain it. You can use version 3.6 for python 2. Python 2 support is being dropped from Django soon anyway.

**Comment by predatell** [comment]
I have found only one thing in code that can broke support for Python 2.7:

"email_to:str = None"

**Comment by bufke** [comment]
I’m currently working as a contractor on various projects because I need to feed my family. These clients pay for features like the recent scheduled reports. If you’d like to pay me to develop continued python 2 support, including ensuring it passes in unit tests against a grid of python versions + django versions, please get in touch.

You are also welcome to fork the project.

Using version 3.6 with python 2 should work just fine for years to come. Supporting future django versions is moot because Django is dropping python 2.

**Comment by predatell** [comment]
https://github.com/burke-software/django-report-builder/pull/277

**Comment by predatell** [comment]
Version 3.6 does not work with python 2.7 and Django 1.11 now! I don't understand about what "years" are you saying?

**Comment by predatell** [comment]
I sent you pull request (saving your time) for fixing support of python 2.7 and fixing bug for Django 1.11.

**Comment by predatell** [comment]
> We follow Django's supported version schedule for new releases. No longer supported versions should use previous versions of report builder.
> 
>     Django - 1.8, 1.10, and 1.11
>     Django Rest Framework 3.4+
>     Python - 3.5 and 3.6.

Every from these versions of Django - 1.8, 1.10, and 1.11 supports python 2.7. There is no stable version of Django with dropped support of python 2.7.

**Comment by bufke** [comment]
This isn't an argument or a democracy. You have no rights to what I do with my time or to argue with me on what takes time. Please refrain from posting on this project.
